/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as TournamentsIdIndexRouteImport } from './routes/tournaments/$id/index'
import { Route as TournamentsIdTeamsRouteImport } from './routes/tournaments/$id/teams'
import { Route as TournamentsIdMatchesRouteImport } from './routes/tournaments/$id/matches'
import { Route as TournamentsIdMatchIdRouteRouteImport } from './routes/tournaments/$id/$matchId/route'
import { Route as TournamentsIdMatchIdMatchRouteImport } from './routes/tournaments/$id/$matchId/match'
import { Route as TournamentsIdMatchIdEventsRouteImport } from './routes/tournaments/$id/$matchId/events'
import { Route as TournamentsIdMatchIdComentaryRouteImport } from './routes/tournaments/$id/$matchId/comentary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdIndexRoute = TournamentsIdIndexRouteImport.update({
  id: '/tournaments/$id/',
  path: '/tournaments/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdTeamsRoute = TournamentsIdTeamsRouteImport.update({
  id: '/tournaments/$id/teams',
  path: '/tournaments/$id/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdMatchesRoute = TournamentsIdMatchesRouteImport.update({
  id: '/tournaments/$id/matches',
  path: '/tournaments/$id/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdMatchIdRouteRoute =
  TournamentsIdMatchIdRouteRouteImport.update({
    id: '/tournaments/$id/$matchId',
    path: '/tournaments/$id/$matchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsIdMatchIdMatchRoute =
  TournamentsIdMatchIdMatchRouteImport.update({
    id: '/match',
    path: '/match',
    getParentRoute: () => TournamentsIdMatchIdRouteRoute,
  } as any)
const TournamentsIdMatchIdEventsRoute =
  TournamentsIdMatchIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => TournamentsIdMatchIdRouteRoute,
  } as any)
const TournamentsIdMatchIdComentaryRoute =
  TournamentsIdMatchIdComentaryRouteImport.update({
    id: '/comentary',
    path: '/comentary',
    getParentRoute: () => TournamentsIdMatchIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/tournaments/$id/$matchId': typeof TournamentsIdMatchIdRouteRouteWithChildren
  '/tournaments/$id/matches': typeof TournamentsIdMatchesRoute
  '/tournaments/$id/teams': typeof TournamentsIdTeamsRoute
  '/tournaments/$id': typeof TournamentsIdIndexRoute
  '/tournaments/$id/$matchId/comentary': typeof TournamentsIdMatchIdComentaryRoute
  '/tournaments/$id/$matchId/events': typeof TournamentsIdMatchIdEventsRoute
  '/tournaments/$id/$matchId/match': typeof TournamentsIdMatchIdMatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/tournaments/$id/$matchId': typeof TournamentsIdMatchIdRouteRouteWithChildren
  '/tournaments/$id/matches': typeof TournamentsIdMatchesRoute
  '/tournaments/$id/teams': typeof TournamentsIdTeamsRoute
  '/tournaments/$id': typeof TournamentsIdIndexRoute
  '/tournaments/$id/$matchId/comentary': typeof TournamentsIdMatchIdComentaryRoute
  '/tournaments/$id/$matchId/events': typeof TournamentsIdMatchIdEventsRoute
  '/tournaments/$id/$matchId/match': typeof TournamentsIdMatchIdMatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournaments/$id/$matchId': typeof TournamentsIdMatchIdRouteRouteWithChildren
  '/tournaments/$id/matches': typeof TournamentsIdMatchesRoute
  '/tournaments/$id/teams': typeof TournamentsIdTeamsRoute
  '/tournaments/$id/': typeof TournamentsIdIndexRoute
  '/tournaments/$id/$matchId/comentary': typeof TournamentsIdMatchIdComentaryRoute
  '/tournaments/$id/$matchId/events': typeof TournamentsIdMatchIdEventsRoute
  '/tournaments/$id/$matchId/match': typeof TournamentsIdMatchIdMatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tournaments'
    | '/tournaments/$id/$matchId'
    | '/tournaments/$id/matches'
    | '/tournaments/$id/teams'
    | '/tournaments/$id'
    | '/tournaments/$id/$matchId/comentary'
    | '/tournaments/$id/$matchId/events'
    | '/tournaments/$id/$matchId/match'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tournaments'
    | '/tournaments/$id/$matchId'
    | '/tournaments/$id/matches'
    | '/tournaments/$id/teams'
    | '/tournaments/$id'
    | '/tournaments/$id/$matchId/comentary'
    | '/tournaments/$id/$matchId/events'
    | '/tournaments/$id/$matchId/match'
  id:
    | '__root__'
    | '/'
    | '/tournaments/'
    | '/tournaments/$id/$matchId'
    | '/tournaments/$id/matches'
    | '/tournaments/$id/teams'
    | '/tournaments/$id/'
    | '/tournaments/$id/$matchId/comentary'
    | '/tournaments/$id/$matchId/events'
    | '/tournaments/$id/$matchId/match'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  TournamentsIdMatchIdRouteRoute: typeof TournamentsIdMatchIdRouteRouteWithChildren
  TournamentsIdMatchesRoute: typeof TournamentsIdMatchesRoute
  TournamentsIdTeamsRoute: typeof TournamentsIdTeamsRoute
  TournamentsIdIndexRoute: typeof TournamentsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/': {
      id: '/tournaments/$id/'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/teams': {
      id: '/tournaments/$id/teams'
      path: '/tournaments/$id/teams'
      fullPath: '/tournaments/$id/teams'
      preLoaderRoute: typeof TournamentsIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/matches': {
      id: '/tournaments/$id/matches'
      path: '/tournaments/$id/matches'
      fullPath: '/tournaments/$id/matches'
      preLoaderRoute: typeof TournamentsIdMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/$matchId': {
      id: '/tournaments/$id/$matchId'
      path: '/tournaments/$id/$matchId'
      fullPath: '/tournaments/$id/$matchId'
      preLoaderRoute: typeof TournamentsIdMatchIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/$matchId/match': {
      id: '/tournaments/$id/$matchId/match'
      path: '/match'
      fullPath: '/tournaments/$id/$matchId/match'
      preLoaderRoute: typeof TournamentsIdMatchIdMatchRouteImport
      parentRoute: typeof TournamentsIdMatchIdRouteRoute
    }
    '/tournaments/$id/$matchId/events': {
      id: '/tournaments/$id/$matchId/events'
      path: '/events'
      fullPath: '/tournaments/$id/$matchId/events'
      preLoaderRoute: typeof TournamentsIdMatchIdEventsRouteImport
      parentRoute: typeof TournamentsIdMatchIdRouteRoute
    }
    '/tournaments/$id/$matchId/comentary': {
      id: '/tournaments/$id/$matchId/comentary'
      path: '/comentary'
      fullPath: '/tournaments/$id/$matchId/comentary'
      preLoaderRoute: typeof TournamentsIdMatchIdComentaryRouteImport
      parentRoute: typeof TournamentsIdMatchIdRouteRoute
    }
  }
}

interface TournamentsIdMatchIdRouteRouteChildren {
  TournamentsIdMatchIdComentaryRoute: typeof TournamentsIdMatchIdComentaryRoute
  TournamentsIdMatchIdEventsRoute: typeof TournamentsIdMatchIdEventsRoute
  TournamentsIdMatchIdMatchRoute: typeof TournamentsIdMatchIdMatchRoute
}

const TournamentsIdMatchIdRouteRouteChildren: TournamentsIdMatchIdRouteRouteChildren =
  {
    TournamentsIdMatchIdComentaryRoute: TournamentsIdMatchIdComentaryRoute,
    TournamentsIdMatchIdEventsRoute: TournamentsIdMatchIdEventsRoute,
    TournamentsIdMatchIdMatchRoute: TournamentsIdMatchIdMatchRoute,
  }

const TournamentsIdMatchIdRouteRouteWithChildren =
  TournamentsIdMatchIdRouteRoute._addFileChildren(
    TournamentsIdMatchIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  TournamentsIdMatchIdRouteRoute: TournamentsIdMatchIdRouteRouteWithChildren,
  TournamentsIdMatchesRoute: TournamentsIdMatchesRoute,
  TournamentsIdTeamsRoute: TournamentsIdTeamsRoute,
  TournamentsIdIndexRoute: TournamentsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
