/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments/index'
import { Route as AdminTournamentsRouteImport } from './routes/admin/tournaments'
import { Route as AdminTournamentRouteImport } from './routes/admin/tournament'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminPlayerRouteImport } from './routes/admin/player'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgetRouteImport } from './routes/_auth/forget'
import { Route as TournamentsIdIndexRouteImport } from './routes/tournaments/$id/index'
import { Route as TournamentsIdTeamsRouteImport } from './routes/tournaments/$id/teams'
import { Route as TournamentsIdMatchesRouteImport } from './routes/tournaments/$id/matches'
import { Route as AdminIdMatchRouteImport } from './routes/admin/$id/match'
import { Route as TournamentsIdMatchIdRouteRouteImport } from './routes/tournaments/$id/$matchId/route'
import { Route as TournamentsIdMatchIdMatchRouteImport } from './routes/tournaments/$id/$matchId/match'
import { Route as TournamentsIdMatchIdEventsRouteImport } from './routes/tournaments/$id/$matchId/events'
import { Route as TournamentsIdMatchIdComentaryRouteImport } from './routes/tournaments/$id/$matchId/comentary'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTournamentRoute = AdminTournamentRouteImport.update({
  id: '/tournament',
  path: '/tournament',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPlayerRoute = AdminPlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgetRoute = AuthForgetRouteImport.update({
  id: '/_auth/forget',
  path: '/forget',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdIndexRoute = TournamentsIdIndexRouteImport.update({
  id: '/tournaments/$id/',
  path: '/tournaments/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdTeamsRoute = TournamentsIdTeamsRouteImport.update({
  id: '/tournaments/$id/teams',
  path: '/tournaments/$id/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdMatchesRoute = TournamentsIdMatchesRouteImport.update({
  id: '/tournaments/$id/matches',
  path: '/tournaments/$id/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdMatchRoute = AdminIdMatchRouteImport.update({
  id: '/$id/match',
  path: '/$id/match',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TournamentsIdMatchIdRouteRoute =
  TournamentsIdMatchIdRouteRouteImport.update({
    id: '/tournaments/$id/$matchId',
    path: '/tournaments/$id/$matchId',
    getParentRoute: () => rootRouteImport,
  } as any)
const TournamentsIdMatchIdMatchRoute =
  TournamentsIdMatchIdMatchRouteImport.update({
    id: '/match',
    path: '/match',
    getParentRoute: () => TournamentsIdMatchIdRouteRoute,
  } as any)
const TournamentsIdMatchIdEventsRoute =
  TournamentsIdMatchIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => TournamentsIdMatchIdRouteRoute,
  } as any)
const TournamentsIdMatchIdComentaryRoute =
  TournamentsIdMatchIdComentaryRouteImport.update({
    id: '/comentary',
    path: '/comentary',
    getParentRoute: () => TournamentsIdMatchIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forget': typeof AuthForgetRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/player': typeof AdminPlayerRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/tournament': typeof AdminTournamentRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/tournaments/$id/$matchId': typeof TournamentsIdMatchIdRouteRouteWithChildren
  '/admin/$id/match': typeof AdminIdMatchRoute
  '/tournaments/$id/matches': typeof TournamentsIdMatchesRoute
  '/tournaments/$id/teams': typeof TournamentsIdTeamsRoute
  '/tournaments/$id': typeof TournamentsIdIndexRoute
  '/tournaments/$id/$matchId/comentary': typeof TournamentsIdMatchIdComentaryRoute
  '/tournaments/$id/$matchId/events': typeof TournamentsIdMatchIdEventsRoute
  '/tournaments/$id/$matchId/match': typeof TournamentsIdMatchIdMatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/forget': typeof AuthForgetRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/player': typeof AdminPlayerRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/tournament': typeof AdminTournamentRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/tournaments/$id/$matchId': typeof TournamentsIdMatchIdRouteRouteWithChildren
  '/admin/$id/match': typeof AdminIdMatchRoute
  '/tournaments/$id/matches': typeof TournamentsIdMatchesRoute
  '/tournaments/$id/teams': typeof TournamentsIdTeamsRoute
  '/tournaments/$id': typeof TournamentsIdIndexRoute
  '/tournaments/$id/$matchId/comentary': typeof TournamentsIdMatchIdComentaryRoute
  '/tournaments/$id/$matchId/events': typeof TournamentsIdMatchIdEventsRoute
  '/tournaments/$id/$matchId/match': typeof TournamentsIdMatchIdMatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/_auth/forget': typeof AuthForgetRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/player': typeof AdminPlayerRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/tournament': typeof AdminTournamentRoute
  '/admin/tournaments': typeof AdminTournamentsRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/tournaments/$id/$matchId': typeof TournamentsIdMatchIdRouteRouteWithChildren
  '/admin/$id/match': typeof AdminIdMatchRoute
  '/tournaments/$id/matches': typeof TournamentsIdMatchesRoute
  '/tournaments/$id/teams': typeof TournamentsIdTeamsRoute
  '/tournaments/$id/': typeof TournamentsIdIndexRoute
  '/tournaments/$id/$matchId/comentary': typeof TournamentsIdMatchIdComentaryRoute
  '/tournaments/$id/$matchId/events': typeof TournamentsIdMatchIdEventsRoute
  '/tournaments/$id/$matchId/match': typeof TournamentsIdMatchIdMatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/forget'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/player'
    | '/admin/team'
    | '/admin/tournament'
    | '/admin/tournaments'
    | '/tournaments'
    | '/tournaments/$id/$matchId'
    | '/admin/$id/match'
    | '/tournaments/$id/matches'
    | '/tournaments/$id/teams'
    | '/tournaments/$id'
    | '/tournaments/$id/$matchId/comentary'
    | '/tournaments/$id/$matchId/events'
    | '/tournaments/$id/$matchId/match'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/forget'
    | '/login'
    | '/register'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/player'
    | '/admin/team'
    | '/admin/tournament'
    | '/admin/tournaments'
    | '/tournaments'
    | '/tournaments/$id/$matchId'
    | '/admin/$id/match'
    | '/tournaments/$id/matches'
    | '/tournaments/$id/teams'
    | '/tournaments/$id'
    | '/tournaments/$id/$matchId/comentary'
    | '/tournaments/$id/$matchId/events'
    | '/tournaments/$id/$matchId/match'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/_auth/forget'
    | '/_auth/login'
    | '/_auth/register'
    | '/admin/dashboard'
    | '/admin/logs'
    | '/admin/player'
    | '/admin/team'
    | '/admin/tournament'
    | '/admin/tournaments'
    | '/tournaments/'
    | '/tournaments/$id/$matchId'
    | '/admin/$id/match'
    | '/tournaments/$id/matches'
    | '/tournaments/$id/teams'
    | '/tournaments/$id/'
    | '/tournaments/$id/$matchId/comentary'
    | '/tournaments/$id/$matchId/events'
    | '/tournaments/$id/$matchId/match'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthForgetRoute: typeof AuthForgetRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  TournamentsIdMatchIdRouteRoute: typeof TournamentsIdMatchIdRouteRouteWithChildren
  TournamentsIdMatchesRoute: typeof TournamentsIdMatchesRoute
  TournamentsIdTeamsRoute: typeof TournamentsIdTeamsRoute
  TournamentsIdIndexRoute: typeof TournamentsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tournament': {
      id: '/admin/tournament'
      path: '/tournament'
      fullPath: '/admin/tournament'
      preLoaderRoute: typeof AdminTournamentRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/player': {
      id: '/admin/player'
      path: '/player'
      fullPath: '/admin/player'
      preLoaderRoute: typeof AdminPlayerRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forget': {
      id: '/_auth/forget'
      path: '/forget'
      fullPath: '/forget'
      preLoaderRoute: typeof AuthForgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/': {
      id: '/tournaments/$id/'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/teams': {
      id: '/tournaments/$id/teams'
      path: '/tournaments/$id/teams'
      fullPath: '/tournaments/$id/teams'
      preLoaderRoute: typeof TournamentsIdTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/matches': {
      id: '/tournaments/$id/matches'
      path: '/tournaments/$id/matches'
      fullPath: '/tournaments/$id/matches'
      preLoaderRoute: typeof TournamentsIdMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id/match': {
      id: '/admin/$id/match'
      path: '/$id/match'
      fullPath: '/admin/$id/match'
      preLoaderRoute: typeof AdminIdMatchRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/tournaments/$id/$matchId': {
      id: '/tournaments/$id/$matchId'
      path: '/tournaments/$id/$matchId'
      fullPath: '/tournaments/$id/$matchId'
      preLoaderRoute: typeof TournamentsIdMatchIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id/$matchId/match': {
      id: '/tournaments/$id/$matchId/match'
      path: '/match'
      fullPath: '/tournaments/$id/$matchId/match'
      preLoaderRoute: typeof TournamentsIdMatchIdMatchRouteImport
      parentRoute: typeof TournamentsIdMatchIdRouteRoute
    }
    '/tournaments/$id/$matchId/events': {
      id: '/tournaments/$id/$matchId/events'
      path: '/events'
      fullPath: '/tournaments/$id/$matchId/events'
      preLoaderRoute: typeof TournamentsIdMatchIdEventsRouteImport
      parentRoute: typeof TournamentsIdMatchIdRouteRoute
    }
    '/tournaments/$id/$matchId/comentary': {
      id: '/tournaments/$id/$matchId/comentary'
      path: '/comentary'
      fullPath: '/tournaments/$id/$matchId/comentary'
      preLoaderRoute: typeof TournamentsIdMatchIdComentaryRouteImport
      parentRoute: typeof TournamentsIdMatchIdRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminPlayerRoute: typeof AdminPlayerRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTournamentRoute: typeof AdminTournamentRoute
  AdminTournamentsRoute: typeof AdminTournamentsRoute
  AdminIdMatchRoute: typeof AdminIdMatchRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminPlayerRoute: AdminPlayerRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTournamentRoute: AdminTournamentRoute,
  AdminTournamentsRoute: AdminTournamentsRoute,
  AdminIdMatchRoute: AdminIdMatchRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface TournamentsIdMatchIdRouteRouteChildren {
  TournamentsIdMatchIdComentaryRoute: typeof TournamentsIdMatchIdComentaryRoute
  TournamentsIdMatchIdEventsRoute: typeof TournamentsIdMatchIdEventsRoute
  TournamentsIdMatchIdMatchRoute: typeof TournamentsIdMatchIdMatchRoute
}

const TournamentsIdMatchIdRouteRouteChildren: TournamentsIdMatchIdRouteRouteChildren =
  {
    TournamentsIdMatchIdComentaryRoute: TournamentsIdMatchIdComentaryRoute,
    TournamentsIdMatchIdEventsRoute: TournamentsIdMatchIdEventsRoute,
    TournamentsIdMatchIdMatchRoute: TournamentsIdMatchIdMatchRoute,
  }

const TournamentsIdMatchIdRouteRouteWithChildren =
  TournamentsIdMatchIdRouteRoute._addFileChildren(
    TournamentsIdMatchIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthForgetRoute: AuthForgetRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  TournamentsIdMatchIdRouteRoute: TournamentsIdMatchIdRouteRouteWithChildren,
  TournamentsIdMatchesRoute: TournamentsIdMatchesRoute,
  TournamentsIdTeamsRoute: TournamentsIdTeamsRoute,
  TournamentsIdIndexRoute: TournamentsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
